# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: dynamic-rendering-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  role: LambdaAtEdgeRole

# you can add packaging information here
package:
  individually: true

functions:
  botHandler:
    handler: botHandler.run
    package:
      exclude:
        - node_modules/**
    timeout: 5
    memorySize: 128
  renderer:
    handler: renderer.run
    package:
      include:
        - node_modules/**
    timeout: 20
    memorySize: 1792

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
resources:
  Resources:
    LambdaAtEdgeRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: LambdaAtEdgeRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole